import "./globals.css";
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-material.css";
import "react-loading-skeleton/dist/skeleton.css";
import "filepond/dist/filepond.min.css";
import "filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css";

import RootLayoutClient from "./_clientLayout";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import type { Metadata } from "next";

import { GeistSans } from "geist/font";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
	title: "Penészmentesítés",
	description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className={GeistSans.className}>
			<UserProvider>
				<body>
					<RootLayoutClient>{children}</RootLayoutClient>
					<SpeedInsights />
				</body>
			</UserProvider>
		</html>
	);
}
